apiVersion: v1
kind: Service
metadata:
  name: http-nodeport
  namespace: flightaware
spec:
  ports:
  - name: http
    {{ if .Values.piaware.nodeport.enable }}
    nodePort: {{ default 30069 .Values.piaware.nodeport.port  }}
    {{ end }}
    port: 8080
    protocol: TCP
    targetPort: 8080
  {{ if .Values.fr24feed.enabled }}
  - name: fr24feed
    {{ if .Values.fr24feed.nodeport.enable }}
    nodePort: {{ default 30072 .Values.fr24feed.nodeport.port  }}
    {{ end }}
    port: 30005
    protocol: TCP
    targetPort: 30005
  {{ end }}
  {{ if .Values.dump1090exporter.enabled }}
  - name: prom-exporter
    {{ if .Values.dump1090exporter.nodeport.enable }}
    nodePort: {{ default 30070 .Values.dump1090exporter.nodeport.port  }}
    {{ end}}
    port: 9105
    protocol: TCP
    targetPort: 9105
  {{ end }}
  {{ if .Values.grafana.enabled }}
  - name: grafana
    {{ if .Values.grafana.nodeport.enable }}
    nodePort: {{ default 30071 .Values.grafana.nodeport.port  }}
    {{ end}}
    port: 3000
    protocol: TCP
    targetPort: 3000
  {{ end }}

  selector:
    app: apps.deployment-flightaware-piaware
  sessionAffinity: None
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: {{ default "flightaware" .Values.namespace | quote }}
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9090'
spec:
  selector:
    app: apps.deployment-flightaware-piaware
  type: NodePort
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: {{ default 30063 .Values.prometheus.nodePort  }}